export default {
  $window: window,
  $document: document,
  $html: document.documentElement,
  $body: document.body,
  $burger: document.querySelector('.burger'),
  $nav: document.querySelector('.header__list'),
  $mobileFiltersOpen: document.querySelector('.catalog-mobile-filters'),
  $storySlider: document.querySelector('.story'),
  $storySliderSlide: document.querySelectorAll('.swiper-slide'),
  $newsSlider: document.querySelector('.news__slider'),
  $menuBtn: document.querySelector('.nav-list__menu'),
  $serviceSlider: document.querySelector('.services__slider'),
  $cursor: document.querySelector('.cursor'),
  $cursorInner: document.querySelector('.cursor-click'),
  $serviseSlider: document.querySelector('.services__items'),
  $serviseSliderItem: document.querySelector('.services__item'),
  $formSend: document.querySelectorAll('.form'),
  $formName: document.querySelectorAll('[data-target=name]'),
  $formEmail: document.querySelectorAll('[data-target=email]'),
  $formTel: document.querySelectorAll('[data-target=tel]'),
  $formCheck: document.querySelectorAll('[data-target=ckeck]'),
  $closeModal: document.querySelectorAll('[data-close=modal]'),
  $openModals: document.querySelectorAll('[data-path=modal-form],[data-path=modal-finish]')
}