export default {
  $window: window,
  $document: document,
  $html: document.documentElement,
  $body: document.body,
  $burger: document.querySelector('.burger'),
  $nav: document.querySelector('.header__list'),
  $mobileFiltersOpen: document.querySelector('.catalog-mobile-filters'),
  $storySlider: document.querySelector('.story'),
  $storySliderSlide: document.querySelectorAll('.swiper-slide'),
  $newsSlider: document.querySelector('.news__slider'),
  $menuBtn: document.querySelector('.nav-list__menu'),
  $serviceSlider: document.querySelector('.services__slider'),
  $cursor: document.querySelector('.cursor'),
  $cursorInner: document.querySelector('.cursor-click'),
  $serviseSlider: document.querySelector('.services__items'),
  $serviseSliderItem: document.querySelector('.services__item'),
  $formSend: document.querySelector('.form'),
  $formSendModal: document.querySelector('.modal .form'),
  $formName: document.querySelector('[data-target=name]'),
  $formNameModal: document.querySelector('.modal [data-target=name]'),
  $formEmail: document.querySelector('[data-target=email]'),
  $formTel: document.querySelector('.wpcf7-form-control-wrap.phone .form__phone'),
  $formTelModal: document.querySelector('.wpcf7-form-control-wrap.phome-mob .form__area'),
  $formCheck: document.querySelector('[data-target=ckeck]'),
  $formCheckModal: document.querySelector('.modal [data-target=ckeck]'),
  $closeModal: document.querySelectorAll('[data-close=modal]'),
  $openModals: document.querySelectorAll('[data-path=modal-form],[data-path=modal-finish]'),
  $headerBtnModal: document.querySelector('.header__list .btn'),
}